//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesag
    {
        public int MesagId { get; set; }
        public string Mesag1 { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
