//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UINE_PHFinalRep
    {
        public int FinalRepID { get; set; }
        public Nullable<int> UIEventID { get; set; }
        public Nullable<int> PHMainID { get; set; }
        public Nullable<int> SigNameID { get; set; }
        public string SigName { get; set; }
        public string SigTitle { get; set; }
        public Nullable<System.DateTime> DtFinalRep { get; set; }
        public string ActiveInd { get; set; }
    }
}
