//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UINE_PrimaryReason
    {
        public int PrimReasonID { get; set; }
        public Nullable<int> UINEID { get; set; }
        public Nullable<int> UIEventID { get; set; }
        public string EmerOrPHcode { get; set; }
        public string EmerOrPHName { get; set; }
        public string BehavCode { get; set; }
        public string BehavName { get; set; }
        public string HealthCode { get; set; }
        public string HealthName { get; set; }
        public string ComCode { get; set; }
        public string ComName { get; set; }
        public string OpCode { get; set; }
        public string OpName { get; set; }
        public string PersonCode { get; set; }
        public string PersonName { get; set; }
        public Nullable<int> AdminRepReasonID { get; set; }
        public string AdminRepReasonName { get; set; }
        public string DESERepCode { get; set; }
        public string DESERepName { get; set; }
        public string ActiveInd { get; set; }
    }
}
