//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UINE_ITSTrauma
    {
        public int ItsTraumaID { get; set; }
        public Nullable<int> ItsID { get; set; }
        public Nullable<int> EventID { get; set; }
        public string NumberTxtID { get; set; }
        public string NumberTxt { get; set; }
        public string TypeTxtID { get; set; }
        public string TypeTxt { get; set; }
        public string SeverityTxtID { get; set; }
        public string SeverityTxt { get; set; }
        public string CommentTxtID { get; set; }
        public string CommentTxt { get; set; }
        public string FormStatus { get; set; }
        public string ActiveInd { get; set; }
    }
}
