//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UINE_PHMain
    {
        public int PHID { get; set; }
        public Nullable<int> UIEventID { get; set; }
        public string NameOfAgency { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string StudentName { get; set; }
        public Nullable<System.DateTime> DateOfRest { get; set; }
        public Nullable<int> GenderID { get; set; }
        public string Gender { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public string ProgramName { get; set; }
        public string SASSID { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<int> SubjPeriodID { get; set; }
        public string SubjPeriod { get; set; }
        public string SendingDistrict { get; set; }
        public Nullable<bool> chkStdIEP { get; set; }
        public string FormStatus { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ActiveInd { get; set; }
        public string AgencyFlag { get; set; }
        public string ProgramGroup { get; set; }
        public Nullable<int> DurationMin { get; set; }
        public Nullable<int> DurationSec { get; set; }
        public Nullable<double> TotalResTimeMin { get; set; }
        public string RestraintInterval { get; set; }
        public string LocationName { get; set; }
        public string OtherLocation { get; set; }
        public Nullable<int> OtherLocationID { get; set; }
    }
}
