//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UINE_PHStdBehCessInj
    {
        public int StdBehCesInjID { get; set; }
        public Nullable<int> UIEventID { get; set; }
        public Nullable<int> PHMainID { get; set; }
        public Nullable<bool> chkActRes { get; set; }
        public Nullable<bool> chkPassive { get; set; }
        public Nullable<bool> chkEmotionDist { get; set; }
        public string DescStdBeh { get; set; }
        public Nullable<bool> chkDetStdCalm { get; set; }
        public Nullable<bool> chkIntervAdm { get; set; }
        public Nullable<bool> chkStaffMedAssis { get; set; }
        public Nullable<bool> chkCesother { get; set; }
        public string DescCess { get; set; }
        public Nullable<bool> chkStdInj { get; set; }
        public string StdInjDesc { get; set; }
        public Nullable<bool> chkStaffInj { get; set; }
        public string StaffInkDesc { get; set; }
        public Nullable<bool> chkNoInj { get; set; }
        public string ActiveInd { get; set; }
    }
}
