//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UINE_AdmRew
    {
        public int ReviewID { get; set; }
        public Nullable<int> UINEID { get; set; }
        public Nullable<int> UIEventID { get; set; }
        public string chkAdmFurRewReq { get; set; }
        public string chkNoAdmRewReq { get; set; }
        public Nullable<int> AdminStaffSignID { get; set; }
        public string AdminStaffSign { get; set; }
        public string AdminStaffSignPos { get; set; }
        public Nullable<System.DateTime> AdminStaffSignDate { get; set; }
        public string FurAdmRewDesc { get; set; }
        public Nullable<int> FurAdmRewsignID { get; set; }
        public string FurAdmRewSignName { get; set; }
        public string FurAdmRewSignPos { get; set; }
        public Nullable<System.DateTime> FurAdmRewSignDate { get; set; }
        public string ActiveInd { get; set; }
    }
}
