//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UINE_Events
    {
        public int UIEventID { get; set; }
        public Nullable<int> UINEUINum { get; set; }
        public Nullable<int> UINEPHNum { get; set; }
        public Nullable<int> UINEITSNum { get; set; }
        public string ActiveInd { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string FormStatus { get; set; }
        public string AgencyFlag { get; set; }
        public Nullable<int> SendEmailID { get; set; }
        public Nullable<int> InitialSubmitID { get; set; }
        public Nullable<int> UIEventNum { get; set; }
    }
}
