//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UINE_PHAdminParent
    {
        public int AdminParID { get; set; }
        public Nullable<int> UIEventID { get; set; }
        public Nullable<int> PHMainID { get; set; }
        public Nullable<int> AdmininformedID { get; set; }
        public string AdminformedName { get; set; }
        public string AdminformedTitle { get; set; }
        public Nullable<int> AdminInfoRepbyID { get; set; }
        public string AdminInfoRepbyName { get; set; }
        public string AdminInfoRepbyTitle { get; set; }
        public Nullable<int> AdminApp20MinsID { get; set; }
        public string AdminApp20MinsName { get; set; }
        public string AdminApp20MinsTitle { get; set; }
        public Nullable<int> RepByApp20MinsID { get; set; }
        public string RepByApp20MinsName { get; set; }
        public string RepByApp20MinsTitle { get; set; }
        public string ParentNotName { get; set; }
        public string ParentPhone { get; set; }
        public Nullable<int> CalledByID { get; set; }
        public string CalledByName { get; set; }
        public string CalledByTitle { get; set; }
        public Nullable<System.DateTime> CalledDate { get; set; }
        public Nullable<System.TimeSpan> CalledTime { get; set; }
        public string DocContactVerbalDesc { get; set; }
        public Nullable<System.DateTime> RepSntDate { get; set; }
        public string RepSntAddress { get; set; }
        public string ActiveInd { get; set; }
    }
}
