//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UINE_PHDeseReq
    {
        public int DESEReqID { get; set; }
        public Nullable<int> UIEventID { get; set; }
        public Nullable<int> PHMainID { get; set; }
        public string DescInjMedCare { get; set; }
        public string DescAntecedent { get; set; }
        public string DescBehJustRest { get; set; }
        public string DescDeEscalation { get; set; }
        public string DescReasHold { get; set; }
        public string DescChildBeh { get; set; }
        public string DescDiscipline { get; set; }
        public string DescReason20Mins { get; set; }
        public string DtTimeParentNot { get; set; }
        public string AdminAppRestName { get; set; }
        public string AdminImmNot { get; set; }
        public string ParentNot24hrsDoc { get; set; }
        public string WritRepSntParent { get; set; }
        public string ActiveInd { get; set; }
    }
}
