//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UINE_FollowupReq
    {
        public int FollowupID { get; set; }
        public Nullable<int> UINEID { get; set; }
        public Nullable<int> UIEventID { get; set; }
        public string FollowupDesc { get; set; }
        public Nullable<int> StaffCompFollReqID { get; set; }
        public string StaffCompFollReqName { get; set; }
        public string StaffCompFollReqPos { get; set; }
        public string ActiveInd { get; set; }
    }
}
