//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UINE_Investigation
    {
        public int InvestID { get; set; }
        public Nullable<int> UINEID { get; set; }
        public Nullable<int> UIEventID { get; set; }
        public string ChkInvNecess { get; set; }
        public string InvestDesc { get; set; }
        public string ChkExecNot { get; set; }
        public string ChkFundorFamilyNot { get; set; }
        public string ChkInvReqNot { get; set; }
        public string ChkDCF { get; set; }
        public Nullable<System.DateTime> DCFDate { get; set; }
        public Nullable<System.TimeSpan> DCFTime { get; set; }
        public string DCFNotTo { get; set; }
        public string DCFNotBy { get; set; }
        public string ChkDPPC { get; set; }
        public Nullable<System.DateTime> DPPCDate { get; set; }
        public Nullable<System.TimeSpan> DPPCTime { get; set; }
        public string DPPCNotTo { get; set; }
        public string DPPCNotBy { get; set; }
        public string ChkDESE { get; set; }
        public Nullable<System.DateTime> DESEDate { get; set; }
        public Nullable<System.TimeSpan> DESETime { get; set; }
        public string DESENotTo { get; set; }
        public string DESENotBy { get; set; }
        public string ChkDEEC { get; set; }
        public Nullable<System.DateTime> DEECDate { get; set; }
        public Nullable<System.TimeSpan> DEECTime { get; set; }
        public string DEECNotTo { get; set; }
        public string DEECNotBy { get; set; }
        public string ChkLEA { get; set; }
        public Nullable<System.DateTime> LEADate { get; set; }
        public Nullable<System.TimeSpan> LEATime { get; set; }
        public string LEANotTo { get; set; }
        public string LEANotBy { get; set; }
        public string ChkFamGuardian { get; set; }
        public Nullable<System.DateTime> FamGuarDate { get; set; }
        public Nullable<System.TimeSpan> FamGuarTime { get; set; }
        public string FamGuarTo { get; set; }
        public string FamGuarBy { get; set; }
        public string ChkDDS { get; set; }
        public Nullable<System.DateTime> DDSDate { get; set; }
        public Nullable<System.TimeSpan> DDSTime { get; set; }
        public string DDSNotTo { get; set; }
        public string DDSNotBy { get; set; }
        public string ActiveInd { get; set; }
    }
}
