//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UINE_ITSMainTable
    {
        public int ItsID { get; set; }
        public Nullable<int> EventID { get; set; }
        public string StudentName { get; set; }
        public string StudentNameValue { get; set; }
        public Nullable<System.DateTime> StudentDate { get; set; }
        public string CompletedOn { get; set; }
        public string CompletedOnValue { get; set; }
        public Nullable<System.DateTime> CompletedOnDate { get; set; }
        public string CompletedBy { get; set; }
        public string CompletedByValue { get; set; }
        public Nullable<int> NumberIndex { get; set; }
        public Nullable<int> SeverityIndex1 { get; set; }
        public Nullable<int> SeverityIndex2 { get; set; }
        public Nullable<int> SeverityIndex3 { get; set; }
        public string RiskLevel { get; set; }
        public Nullable<bool> MNeNursing { get; set; }
        public Nullable<bool> ERVisit { get; set; }
        public string FormStatus { get; set; }
        public string ActiveInd { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string AgencyFlag { get; set; }
    }
}
