//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UINE_DirNurSign
    {
        public int DirNurRewID { get; set; }
        public Nullable<int> UINEID { get; set; }
        public Nullable<int> UIEventID { get; set; }
        public string chkResDir { get; set; }
        public Nullable<int> ResDirSigID { get; set; }
        public string ResDirsigName { get; set; }
        public string ResDirSigPos { get; set; }
        public Nullable<System.DateTime> ResDirSigDate { get; set; }
        public string ChkSchoolDir { get; set; }
        public Nullable<int> SchooDirSigID { get; set; }
        public string SchoolDirSigName { get; set; }
        public string schoolDirSigPos { get; set; }
        public Nullable<System.DateTime> ScholDirSigDate { get; set; }
        public string ChkNurPerson { get; set; }
        public Nullable<int> NursingSigID { get; set; }
        public string NursingSigName { get; set; }
        public string NursingSigPos { get; set; }
        public Nullable<System.DateTime> NursingSigDate { get; set; }
        public string ActiveInd { get; set; }
    }
}
