//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UINE_PHPrecJust
    {
        public int PrecJustID { get; set; }
        public Nullable<int> UIEventID { get; set; }
        public Nullable<int> PHMainID { get; set; }
        public Nullable<bool> chkTask { get; set; }
        public Nullable<bool> chkLeisure { get; set; }
        public string DescActivityPrior { get; set; }
        public Nullable<bool> chkTantrum { get; set; }
        public Nullable<bool> chkSelfInj { get; set; }
        public Nullable<bool> chkAggression { get; set; }
        public string DescBehPromptRest { get; set; }
        public Nullable<bool> chkPrecAdaptiveBeh { get; set; }
        public Nullable<bool> chkstaffRedTask { get; set; }
        public Nullable<bool> chkOppStdAdaptiveBeh { get; set; }
        public Nullable<bool> chkStaffMovAway { get; set; }
        public Nullable<bool> chkNonPhysicalNotEff { get; set; }
        public Nullable<bool> chkprotectfromSerHarm { get; set; }
        public Nullable<bool> chkprotectotherstd { get; set; }
        public Nullable<bool> chkblockRed { get; set; }
        public string ActiveInd { get; set; }
    }
}
