//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UINE_PHRestUsed
    {
        public int RestUsedID { get; set; }
        public Nullable<int> UIEventID { get; set; }
        public Nullable<int> PHMainID { get; set; }
        public Nullable<bool> chkCPISeatPosHand { get; set; }
        public Nullable<bool> chkCPIstandPostHand { get; set; }
        public Nullable<bool> chkCPIChldContStand { get; set; }
        public Nullable<bool> chkCPIChldContSeat { get; set; }
        public Nullable<bool> chkCPITeamCntr { get; set; }
        public Nullable<bool> chkCPIIntCntrSeat { get; set; }
        public Nullable<bool> chkCPIIntCntrStand { get; set; }
        public Nullable<bool> chkCPIAPSStand { get; set; }
        public Nullable<bool> chkCPIAPSErFloor { get; set; }
        public string ActiveInd { get; set; }
        public Nullable<bool> chksmallPVerCar { get; set; }
        public Nullable<bool> chksmallPHorCar { get; set; }
        public string Holds { get; set; }
    }
}
