//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UINE_FinalProc
    {
        public int FinalProcID { get; set; }
        public Nullable<int> UIEventID { get; set; }
        public Nullable<int> UINEID { get; set; }
        public Nullable<System.DateTime> FinalReportDate { get; set; }
        public string ChkFinalDCF { get; set; }
        public string ChkFinalDPPC { get; set; }
        public string ChkFinalDESE { get; set; }
        public string ChkFinalDEEC { get; set; }
        public string ChkFinalLEA { get; set; }
        public string ChkFinalFamGuar { get; set; }
        public string ActiveInd { get; set; }
    }
}
