//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UINE_Injury
    {
        public int InjID { get; set; }
        public Nullable<int> UINEID { get; set; }
        public Nullable<int> UIEventID { get; set; }
        public string chkstdFirstAid { get; set; }
        public string chkstdDigitalPic { get; set; }
        public string chkstdITS { get; set; }
        public string chkstdInjWBC { get; set; }
        public string chkstdParentNot { get; set; }
        public string chkstdParentCaseNote { get; set; }
        public string chkstaffWorkersComp { get; set; }
        public string chkstaffDigitalPic { get; set; }
        public string chkstaffITS { get; set; }
        public string ActiveInd { get; set; }
    }
}
