//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UINE_PHPersons
    {
        public int PersonsInvolID { get; set; }
        public Nullable<int> UIEventID { get; set; }
        public Nullable<int> PHMainID { get; set; }
        public Nullable<int> Per1ID { get; set; }
        public string Per1Name { get; set; }
        public string Per1Title { get; set; }
        public Nullable<bool> chkPer1BreathMngr { get; set; }
        public Nullable<bool> chkPer1LeadMngr { get; set; }
        public Nullable<bool> chkPer1PriorTrain { get; set; }
        public Nullable<int> Per2ID { get; set; }
        public string Per2Name { get; set; }
        public string Per2Title { get; set; }
        public Nullable<bool> chkPer2BreathMngr { get; set; }
        public Nullable<bool> chkPer2LeadMngr { get; set; }
        public Nullable<bool> chkPer2PriorTrain { get; set; }
        public Nullable<int> Per3ID { get; set; }
        public string Per3Name { get; set; }
        public string Per3Title { get; set; }
        public Nullable<bool> chkPer3BreathMngr { get; set; }
        public Nullable<bool> chkPer3LeadMngr { get; set; }
        public Nullable<bool> chkPer3PriorTrain { get; set; }
        public Nullable<int> Obsrv1ID { get; set; }
        public string Obsrv1Name { get; set; }
        public string Obsrv1Title { get; set; }
        public Nullable<bool> chkObsrv1BreathMngr { get; set; }
        public Nullable<bool> chkObsrv1LeadMgr { get; set; }
        public Nullable<bool> chkObsrv1PriorTrain { get; set; }
        public Nullable<int> Obsrv2ID { get; set; }
        public string Obsrv2Name { get; set; }
        public string Obsrv2Title { get; set; }
        public Nullable<bool> chkObsrv2BreathMngr { get; set; }
        public Nullable<bool> chkObsrv2LeadMgr { get; set; }
        public Nullable<bool> chkObsrv2PriorTrain { get; set; }
        public Nullable<int> Obsrv3ID { get; set; }
        public string Obsrv3Name { get; set; }
        public string Obsrv3Title { get; set; }
        public Nullable<bool> chkObsrv3BreathMngr { get; set; }
        public Nullable<bool> chkObsrv3LeadMgr { get; set; }
        public Nullable<bool> chkObsrv3PriorTrain { get; set; }
        public string ActiveInd { get; set; }
    }
}
