//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UINE_Lookup
    {
        public int UINELookupID { get; set; }
        public string LookupType { get; set; }
        public string LookupCode { get; set; }
        public string LookupName { get; set; }
        public string LookupDesc { get; set; }
        public string ActiveInd { get; set; }
    }
}
