//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UINE_UpdateData
    {
        public int UpdateDataID { get; set; }
        public Nullable<int> UIEventID { get; set; }
        public Nullable<int> FormID { get; set; }
        public string FormType { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string ActiveInd { get; set; }
    }
}
