//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WBC_MainDataTable
    {
        public int WBCID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string ClientName { get; set; }
        public string LabelID { get; set; }
        public string IdentifiedInitials { get; set; }
        public Nullable<System.DateTime> IdentifiedDate { get; set; }
        public Nullable<System.TimeSpan> IdentifiedTime { get; set; }
        public Nullable<bool> FamilyNotify { get; set; }
        public Nullable<System.DateTime> FamilyNotifyDate { get; set; }
        public Nullable<System.TimeSpan> FamilyNotifyTime { get; set; }
        public Nullable<bool> UICompleted { get; set; }
        public string UIRNumber { get; set; }
        public Nullable<System.DateTime> UIDate { get; set; }
        public Nullable<System.TimeSpan> UITime { get; set; }
        public Nullable<bool> NurseNotify { get; set; }
        public string NurseNotifyName { get; set; }
        public Nullable<int> NurseNotifyID { get; set; }
        public Nullable<System.DateTime> NurseNotifyDate { get; set; }
        public Nullable<System.TimeSpan> NurseNotifyTime { get; set; }
        public Nullable<bool> AdminNotify { get; set; }
        public string AdminNotifyName { get; set; }
        public Nullable<int> AdminNotifyID { get; set; }
        public Nullable<System.DateTime> AdminNotifyDate { get; set; }
        public Nullable<System.TimeSpan> AdminNotifyTime { get; set; }
        public string InjuryOriginText { get; set; }
        public string InjuryOriginVal { get; set; }
        public string InjuryLocText { get; set; }
        public string InjuryLocVal { get; set; }
        public string InjuryTypeText { get; set; }
        public string InjuryTypeVal { get; set; }
        public Nullable<bool> SITrauma { get; set; }
        public string AdditionalNotes { get; set; }
        public string ClientResLocText { get; set; }
        public string ClientResLocVal { get; set; }
        public string ClientDayLocText { get; set; }
        public string ClientDayLocVal { get; set; }
        public string SubmittedByName { get; set; }
        public Nullable<int> SubmittedByID { get; set; }
        public Nullable<System.DateTime> SubmittedByDate { get; set; }
        public Nullable<System.TimeSpan> SubmittedByTime { get; set; }
        public string SubmittedByPosition { get; set; }
        public string ClosedByName { get; set; }
        public Nullable<int> ClosedByID { get; set; }
        public Nullable<System.DateTime> ClosedByDate { get; set; }
        public Nullable<System.TimeSpan> ClosedByTime { get; set; }
        public string SelectedLocName { get; set; }
        public string SelectedLocVal { get; set; }
        public Nullable<bool> blank3 { get; set; }
        public Nullable<bool> blank4 { get; set; }
        public Nullable<bool> blank5 { get; set; }
        public string WBCStatus { get; set; }
        public string ActiveStatus { get; set; }
    }
}
