//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WBC_LookupTable
    {
        public int LookupID { get; set; }
        public string QualifyingID { get; set; }
        public string LabelNo { get; set; }
        public string BodyPartIDLvl1 { get; set; }
        public string BodyPartIDLvl2 { get; set; }
        public string BodyPartIDLvl3 { get; set; }
        public string LabelLocFtorBk { get; set; }
        public string CascadingDdlID { get; set; }
        public string DdlValue { get; set; }
        public string DdlText { get; set; }
        public string ActiveStatus { get; set; }
    }
}
