//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WBC_UpdateData
    {
        public int UpdateID { get; set; }
        public Nullable<int> WBCID { get; set; }
        public string UpdatedByName { get; set; }
        public Nullable<int> UpdatedByID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.TimeSpan> UpdateTime { get; set; }
        public string UpdateStatus { get; set; }
    }
}
