//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZHT_MTMain
    {
        public int MTID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public string ProgramName { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string ClientName { get; set; }
        public Nullable<System.DateTime> MTDate { get; set; }
        public Nullable<System.TimeSpan> MTTime { get; set; }
        public Nullable<int> MTCodeID { get; set; }
        public string MTcodeType { get; set; }
        public string MTComments { get; set; }
        public Nullable<int> MTSubmittedBy { get; set; }
        public Nullable<System.DateTime> MTSubmittedOn { get; set; }
        public Nullable<int> MTModifiedBy { get; set; }
        public Nullable<System.DateTime> MTModifiedOn { get; set; }
        public string MTEmailStatus { get; set; }
        public string ActiveInd { get; set; }
    }
}
