//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZHT_UTMain
    {
        public int UTID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public string ProgramName { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string ClientName { get; set; }
        public Nullable<System.DateTime> UTDate { get; set; }
        public Nullable<System.TimeSpan> UTTime { get; set; }
        public Nullable<int> UTCodeID { get; set; }
        public string UTCodeType { get; set; }
        public string UTComments { get; set; }
        public Nullable<int> UTSubmittedby { get; set; }
        public Nullable<System.DateTime> UTSubmittedOn { get; set; }
        public Nullable<int> UTModifiedBy { get; set; }
        public Nullable<System.DateTime> UTModifiedOn { get; set; }
        public string UTEmailStatus { get; set; }
        public string ActiveInd { get; set; }
    }
}
