//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZHT_STMainTable
    {
        public int STID { get; set; }
        public int StudentID { get; set; }
        public string ClientName { get; set; }
        public System.DateTime STDate { get; set; }
        public System.TimeSpan STTime { get; set; }
        public string STDurMin { get; set; }
        public string STDurSec { get; set; }
        public int SubmittedByID { get; set; }
        public string SubmittedByName { get; set; }
        public System.DateTime SubmissionDate { get; set; }
        public System.TimeSpan SubmissionTime { get; set; }
        public bool Unconsious { get; set; }
        public bool Incontinent { get; set; }
        public bool BreatheNormal { get; set; }
        public bool Speech { get; set; }
        public bool Flushed { get; set; }
        public bool Cyanotic { get; set; }
        public bool Epileptic { get; set; }
        public bool Limp { get; set; }
        public bool Rigid { get; set; }
        public bool Spastic { get; set; }
        public bool EyeUp { get; set; }
        public bool EyeDown { get; set; }
        public bool EyeLeft { get; set; }
        public bool EyeRight { get; set; }
        public bool EyeStare { get; set; }
        public bool Face { get; set; }
        public bool Body { get; set; }
        public bool LSide { get; set; }
        public bool RSide { get; set; }
        public bool LLimb { get; set; }
        public bool RLimb { get; set; }
        public bool Head { get; set; }
        public bool AbOther { get; set; }
        public string AbExplain { get; set; }
        public bool Asleep { get; set; }
        public bool Drowsy { get; set; }
        public bool Confused { get; set; }
        public bool Self { get; set; }
        public bool VNS { get; set; }
        public bool VNS1Time { get; set; }
        public bool VNS2Time { get; set; }
        public bool VNS3Time { get; set; }
        public bool VNS4Time { get; set; }
        public bool VNS5Time { get; set; }
        public bool VNSNA { get; set; }
        public bool VNS1Swipe { get; set; }
        public bool VNS2Swipe { get; set; }
        public bool VNS3Swipe { get; set; }
        public bool VNS4Swipe { get; set; }
        public bool VNS5Swipe { get; set; }
        public bool NurseNotify { get; set; }
        public Nullable<int> NurseID { get; set; }
        public string NurseName { get; set; }
        public Nullable<System.DateTime> NurseDate { get; set; }
        public Nullable<System.TimeSpan> NurseTime { get; set; }
        public string Precipitating { get; set; }
        public string Comments { get; set; }
        public string STStatus { get; set; }
        public string ActiveStatus { get; set; }
        public string DiastatVal { get; set; }
        public Nullable<bool> Call911Val { get; set; }
        public string PlacementVal { get; set; }
        public string PlacementTxt { get; set; }
    }
}
