//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZHT_FIGoals
    {
        public int GoalID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> Goal { get; set; }
        public Nullable<int> SubmittedBy { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public Nullable<System.TimeSpan> SubmissionTime { get; set; }
        public string ActiveStatus { get; set; }
    }
}
