//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZHT_CDCGrowthDt
    {
        public int dtID { get; set; }
        public string DtType { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<double> AgeOrST { get; set; }
        public Nullable<double> P3 { get; set; }
        public Nullable<double> P5 { get; set; }
        public Nullable<double> P10 { get; set; }
        public Nullable<double> P25 { get; set; }
        public Nullable<double> P50 { get; set; }
        public Nullable<double> P75 { get; set; }
        public Nullable<double> P85 { get; set; }
        public Nullable<double> P90 { get; set; }
        public Nullable<double> P95 { get; set; }
        public Nullable<double> P97 { get; set; }
    }
}
