//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZHT_BMIMainTable
    {
        public int BMIID { get; set; }
        public int StudentID { get; set; }
        public string ClientName { get; set; }
        public System.DateTime DateOfBMI { get; set; }
        public Nullable<double> BMI { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Height { get; set; }
        public string MonthBMIVal { get; set; }
        public string MonthBMIText { get; set; }
        public string YearBMIVal { get; set; }
        public string YearBMIText { get; set; }
        public string PeriodBMIVal { get; set; }
        public string PeriodBMIText { get; set; }
        public string Comments { get; set; }
        public System.DateTime SubmittedDate { get; set; }
        public System.TimeSpan SubmittedTime { get; set; }
        public int SubmittedByID { get; set; }
        public string SubmittedByName { get; set; }
        public string M1MonthVal { get; set; }
        public string M1YearVal { get; set; }
        public string M3MonthVal { get; set; }
        public string M3YearVal { get; set; }
        public string M6MonthVal { get; set; }
        public string M6YearVal { get; set; }
        public string BMIStatus { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<int> AgeInMnthAtBMI { get; set; }
        public Nullable<double> HeightIncm { get; set; }
        public string PlacementVal { get; set; }
        public string PlacementTxt { get; set; }
    }
}
