//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZHT_FIMainTable
    {
        public int FIid { get; set; }
        public Nullable<int> LocID { get; set; }
        public string LocName { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string ClientName { get; set; }
        public Nullable<System.DateTime> FIDate { get; set; }
        public Nullable<System.TimeSpan> FITime { get; set; }
        public Nullable<int> FIQty { get; set; }
        public string Comments { get; set; }
        public Nullable<int> SubmittedID { get; set; }
        public string SubmitName { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public Nullable<System.TimeSpan> SubmissionTime { get; set; }
        public Nullable<int> FIGoalID { get; set; }
        public string FormStatus { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<int> FIOffer { get; set; }
        public string FITypeVal { get; set; }
        public string FITypeTxt { get; set; }
    }
}
