//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZHT_UpdateData
    {
        public int HTId { get; set; }
        public string ModuleName { get; set; }
        public string ModuleID { get; set; }
        public string UpdateFlag { get; set; }
        public string UpdatedByID { get; set; }
        public string UpdatedByName { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateTime { get; set; }
    }
}
