//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZHT_BMMain
    {
        public int BMID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public string ProgramName { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string ClientName { get; set; }
        public Nullable<System.DateTime> BMDate { get; set; }
        public Nullable<System.TimeSpan> BMTime { get; set; }
        public Nullable<int> BMCodeID { get; set; }
        public string BMCodeType { get; set; }
        public string BMComments { get; set; }
        public Nullable<int> BMSubmittedby { get; set; }
        public Nullable<System.DateTime> BMSubmittedOn { get; set; }
        public Nullable<int> BMModifiedBy { get; set; }
        public Nullable<System.DateTime> BMModifiedOn { get; set; }
        public string BMEmailStatus { get; set; }
        public string ActiveInd { get; set; }
    }
}
