//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZHT_BMNotifEmail
    {
        public int BMEMID { get; set; }
        public Nullable<System.DateTime> EMDate { get; set; }
        public string EMTime { get; set; }
        public string EMSentFlag { get; set; }
    }
}
