//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZHT_Lookup
    {
        public int HTLookupID { get; set; }
        public string HTLookupapp { get; set; }
        public string HTLookupType { get; set; }
        public string HTLookupCode { get; set; }
        public string HTLookupName { get; set; }
        public string HTLookupDesc { get; set; }
        public string HTActiveInd { get; set; }
    }
}
